### ISSUE TITLE
Audio Focus sticking

### ISSUE THREAD

**Issue by silverchris** [silverchris/openauto#15]
Sometimes the audio focus gets stuck on navigation or voice commands, instead of releasing back to whatever was playing

**Comment by YouHusam** [comment]
Can't find /tmp/autoapp

![Uploading Screenshot_20220719-205321_Termux.jpg…]()

**Comment by YouHusam** [comment]
![Screenshot_20220719-205716_Termux](https://user-images.githubusercontent.com/5736950/179817679-7cb92cee-a695-4747-bf6e-f8d18d33a06e.jpg)

**Comment by silverchris** [comment]
Oh, forgot that I don't have it set to default @YouHusam 

if you create /mnt/data_persist/dev/bin/autoapp_configuration.toml with the following settings, it will log :)

```
lefthandDrive = true
hideClock = true
enableTouchscreen = true
wifiPort = 30515
logLevel = "debug"
logFile = "/tmp/autoapp.log"
```

**Comment by YouHusam** [comment]
Hey I'm attaching log with this email.

Let me know if you can't see it.

I had problems with sound and also backup camera.

Thank you very much

**Comment by silverchris** [comment]
@YouHusam what version of CMU Firmware?

**Comment by YouHusam** [comment]
@silverchris  v59.00.545
What version do you support?

**Comment by silverchris** [comment]
@YouHusam 
I do want to support that version, but I think 71.00.100 works better, as we can hijack some of the built in Android Auto functions for our usage. It doesn't require the USB hardware upgrade, as well.
Let me do some digging around :)

**Comment by YouHusam** [comment]
I'm fine with upgrading I'll check if I'll lose some of the tweaks. And I already got the usb upgrade, unofficial from AliExpress if it helps I can install it.

**Comment by silverchris** [comment]
I haven't actually tried it with the hardware, as I don't have it

**Comment by YouHusam** [comment]
> but I think 71.00.100 works better

Did you mean 70.00.100? I can't find anything for 71.00.100

**Comment by YouHusam** [comment]
I don't know what happened but after the update to v70.00.100 it didn't work at first aa was opening and closing on my phone with nothing coming on the screen, I thought it was a bad cable but I tried others and no luck. and after trying to reinstall and trying to install tweaks it no longer shows in the app menu.

Any ideas?
Usb works to install tweaks and the aa app

![20220722_013213](https://user-images.githubusercontent.com/5736950/180326427-86c273b9-4592-4c1b-a499-366f9923ccbb.jpg)

![SmartSelect_20220722-013623_Termux](https://user-images.githubusercontent.com/5736950/180326602-15ab31e5-865c-42b9-a2a8-ba5f2a6a8122.jpg)

**Comment by silverchris** [comment]
Hmmm you could try just doing
mount -o remount,rw /
./openauto_installer.run

**Comment by YouHusam** [comment]
![Screenshot_20220722-015057_Termux](https://user-images.githubusercontent.com/5736950/180328278-fa7fbb0e-d222-4833-b2fd-7a0bd0708f4f.jpg)

Still nothing, I must've messed up something, I'll try to reinstall firmware tomorrow. Unless you have another idea

**Comment by silverchris** [comment]
> ![Screenshot_20220722-015057_Termux](https://user-images.githubusercontent.com/5736950/180328278-fa7fbb0e-d222-4833-b2fd-7a0bd0708f4f.jpg)
> 
> Still nothing, I must've messed up something, I'll try to reinstall firmware tomorrow. Unless you have another idea

Does it work on USB?
anything in /tmp/autoapp?

**Comment by YouHusam** [comment]
I don't think it's working at all, but here's the log

I tried restarting with smctl but it only says it ran successfully and nothing happens

![Screenshot_20220722-015818_Termux](https://user-images.githubusercontent.com/5736950/180328850-c54b19ca-57dd-4d53-9492-ce7c8b62df45.jpg)

**Comment by YouHusam** [comment]
Maybe I need pr #13 because I don't have a HUD?

**Comment by silverchris** [comment]
> Maybe I need pr #13 because I don't have a HUD?

Hmmm, it looks like wifi might not be on? not sure why usb isn't working.

Can you see the wireless from the CMU?

**Comment by YouHusam** [comment]
I didn't install the WiFi tweak, I've been using usb. WiFi is connected to my phone and I'm using it for ssh. I don't know what's going on but I think I just messed up the files while trying to get it to work.
Anyway I'll try tomorrow since it's too late now, and if nothing worked I'll just reinstall the firmware and wish for the best.

Thank you very much for your help I really appreciate it

**Comment by YouHusam** [comment]
I just tried everything I could, install from an older commit, remove all tweaks and reinstall firmware. I always get back to the same issue, aa keeps crashing and restarting, here is an interesting log entry:

```
186.656 I [InputService.cpp] [InputService] start.
186.656 D [AAPA.cpp] [void AAPA::AAConnected(bool)] AAConnected1
186.656 I [autoapp.cpp] Android Auto Connected
186.657 E [AndroidAutoEntity.cpp] [virtual void autoapp::service::AndroidAutoEntity::onChannelError(const aasdk::error::Error&)] [AndroidAutoEntity] channel error: AaSdk error code: 10, native code: 4294967292
186.657 I [App.cpp] [App] onAndroidAutoQuit.
```

log file: https://drive.google.com/file/d/1LLul4Pt1dJKvOJc0WN7-VM0f72gLZB8r/view?usp=sharing

**Comment by YouHusam** [comment]
Installing the USB retrofit seems to fix the problem, I guess it was a voltage issue.

**Comment by YouHusam** [comment]
@silverchris Tested your latest commits this morning on my way to work. Seems fine, still have the same problems:
1. When music is playing, no other sound plays
2. When connected to the car initially there's no sound at all, until I exit AA (long press on back button), turn on FM Radio and then go back and play something.

Couldn't get logs because I was late for work, I will pull them on my way back home.
Let me know if you want me to open separate github issues with these bugs.
Other than that, it's amazing as always, thank you very much

**Comment by YouHusam** [comment]
New log: https://drive.google.com/file/d/1M-Af6chrLu5tQSH5qaIzxWS2vYJneRhA/view?usp=drivesdk

In the end it crashed, initially audio didn't work until I pressed the Google assistant button

**Comment by silverchris** [comment]
@YouHusam Try the latest commit, and see if that helps out with the audio focus issue!

**Comment by YouHusam** [comment]
> @YouHusam Try the latest commit, and see if that helps out with the audio focus issue!

@silverchris so much better thank you, but still can't hear navigation sounds when playing music. But it's so much more stable now

**Comment by silverchris** [comment]
OK, that's a new problem.
Android Auto doesn't appear to be routing the audio for navigation through the media stream. It turns down whatever is playing.

If you are listening to another source that isn't Android Auto, it plays navigation fine...

**Comment by YouHusam** [comment]
> OK, that's a new problem. Android Auto doesn't appear to be routing the audio for navigation through the media stream. It turns down whatever is playing.
> 
> If you are listening to another source that isn't Android Auto, it plays navigation fine...

Yep and it's not only navigation, also notifications and Google assistant. It's the only issue keeping me from using it always

**Comment by silverchris** [comment]
@YouHusam try this commit https://github.com/silverchris/openauto/commit/f893ce9913b34d7d3fadb6bcd6a237ea8cc0ae7f!

**Comment by YouHusam** [comment]
> @YouHusam try this commit [f893ce9](https://github.com/silverchris/openauto/commit/f893ce9913b34d7d3fadb6bcd6a237ea8cc0ae7f)!

Seems to be working! Thank you very much

Still getting an issue with sound when initially connecting, if I play music it doesn't work until I pressed the assistant button then cancel it

**Comment by silverchris** [comment]
https://github.com/silverchris/openauto/releases/tag/v1.0.4
Hey @YouHusam try this one and see if it works without playing around with the assistant button :)

**Comment by YouHusam** [comment]
@silverchris I just tested it briefly and it seems to work. Thank you very much!

**Comment by silverchris** [comment]
Resolved in https://github.com/silverchris/openauto/commit/4ff5349ab1411df0627623231d09e4cf26f46e2b

**Comment by YouHusam** [comment]
It seems like the first time I connect after the car turns on audio doesn't work, no tricks get it to work except disconnecting and reconnecting my phone and it works again. Not a big issue just a little inconvenient.

**Comment by YouHusam** [comment]
Also not getting audio focus after a call

**Comment by silverchris** [comment]
> Also not getting audio focus after a call
That was an easy fix for not starting after a call :)

Can you grab a log for when it won't start audio on the first connect?

**Comment by YouHusam** [comment]
@silverchris  logs here:
https://drive.google.com/file/d/1O67uVB2wXsJLY1m2I6u5FGYCGd4p120E/view?usp=drivesdk

**Comment by silverchris** [comment]
That looks like an old log? Or a previous build? Doesn't look like it is using AAMedia and AAGuidence like 1.0.4 should be

**Comment by YouHusam** [comment]
@silverchris could be it was an old file, try this:
https://drive.google.com/file/d/1OCMK8RvxJwrBO3bo_4d9XT-vIb_Xkmzk/view?usp=drivesdk

**Comment by silverchris** [comment]
> @silverchris could be it was an old file, try this: https://drive.google.com/file/d/1OCMK8RvxJwrBO3bo_4d9XT-vIb_Xkmzk/view?usp=drivesdk

See if it works better with this version https://github.com/silverchris/openauto/releases/tag/v1.0.5

**Comment by silverchris** [comment]
actually, try this one https://github.com/silverchris/openauto/releases/tag/v1.0.6
